name: Run Python script every 12 hours or on demand

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 1
            token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python import_requests.py

      - name: Commit and push if it's not a pull request
        run: |
          git config --local user.email "albionfreemarket@gmail.com"
          git config --local user.name "JPCodeCraft"
          git add us_name_mappings.json
          git commit -m "Add changes" -a || echo "No changes to commit"
          git push
